# permissions for end users to edit kmskeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kmskey-editor-role
rules:
- apiGroups:
  - cert-manager.skyscanner.net
  resources:
  - kmskeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.skyscanner.net
  resources:
  - kmskeys/status
  verbs:
  - get
