# permissions for end users to view kmskeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kmskey-viewer-role
rules:
- apiGroups:
  - cert-manager.skyscanner.net
  resources:
  - kmskeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.skyscanner.net
  resources:
  - kmskeys/status
  verbs:
  - get
